[toolchain]
package_manager = "bun"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.localnet]
magicblock_tutorial = "H121vCEEaieHhrtdCNrs3DhtjrVptuJaxKKvaYy92Ttv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 1000000 tests/*.test.ts"

[hooks]
