[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
magicblock_tutorial = "9oiti6VtiPXPbhSSvFHgZZDomp7SzD8Jd3JvEbcZXW4y"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
