[toolchain]
anchor_version = "0.32.1"
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.devnet]
magicblock_tutorial = "Bv4p1TKzfmuUzZDmVCe2KzmY65ShCj7xbZn2Uc8qSxQv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bunx vitest run --config vitest.config.ts tests/*.test.ts"
